# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.cz/property_contact_mallformed_address.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.nic.cz.rb'

describe Whois::Record::Parser::WhoisNicCz, "property_contact_mallformed_address.expected" do

  before(:each) do
    file = fixture("responses", "whois.nic.cz/property_contact_mallformed_address.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts[0].address.should       == "Zavodní 2453/28\nKaviná-Nové Město \n73506\nCZ"
    end
  end
end
